#%RAML 1.0 ResourceType

resourceTypes:
  errorResponse:
    description: Resource type for error responses
    responses:
      400:
        description: Bad Request
      500:
        description: Internal Server Error